/* eslint-disable */
export const LOGIN_CONSTANTS = {
  LOGIN_LOADING: 'LOGIN_LOADING',
  LOGIN_SUCESS: 'LOGIN_SUCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
};
export const FORGOT_CONSTANTS = {
  FORGOT_LOADING: 'FORGOT_LOADING',
  FORGOT_SUCESS: 'FORGOT_SUCESS',
  FORGOT_ERROR: 'FORGOT_ERROR',
};

export const VIEW_ADMIN_CONSTANT = {
  VIEW_ADMIN_LOADING: 'VIEW_ADMIN_LOADING',
  VIEW_ADMIN_SUCCESS: 'VIEW_ADMIN_SUCCESS',
  VIEW_ADMIN_ERROR: 'VIEW_ADMIN_ERROR',
};
export const VIEW_DIRECTOR_CONSTANT = {
  VIEW_DIRECTOR_LOADING: 'VIEW_DIRECTOR_LOADING',
  VIEW_DIRECTOR_SUCCESS: 'VIEW_DIRECTOR_SUCCESS',
  VIEW_DIRECTOR_ERROR: 'VIEW_DIRECTOR_ERROR',
};

export const VIEW_DEPO_CONSTANT = {
  VIEW_DEPO_LOADING: 'VIEW_DEPO_LOADING',
  VIEW_DEPO_SUCCESS: 'VIEW_DEPO_SUCCESS',
  VIEW_DEPO_ERROR: 'VIEW_DEPO_ERROR',
};
export const VIEW_DELIVERYSTAFF_CONSTANT = {
  VIEW_DELIVERYSTAFF_LOADING: 'VIEW_DELIVERYSTAFF_LOADING',
  VIEW_DELIVERYSTAFF_SUCCESS: 'VIEW_DELIVERYSTAFF_SUCCESS',
  VIEW_DELIVERYSTAFF_ERROR: 'VIEW_DELIVERYSTAFF_ERROR',
};
export const VIEW_AM_CONSTANT = {
  VIEW_AM_LOADING: 'VIEW_AM_LOADING',
  VIEW_AM_SUCCESS: 'VIEW_AM_SUCCESS',
  VIEW_AM_ERROR: 'VIEW_AM_ERROR',
};
export const VIEW_RSM_CONSTANT = {
  VIEW_RSM_LOADING: 'VIEW_RSM_LOADING',
  VIEW_RSM_SUCCESS: 'VIEW_RSM_SUCCESS',
  VIEW_RSM_ERROR: 'VIEW_RSM_ERROR',
};
export const VIEW_SM_CONSTANT = {
  VIEW_SM_LOADING: 'VIEW_SM_LOADING',
  VIEW_SM_SUCCESS: 'VIEW_SM_SUCCESS',
  VIEW_SM_ERROR: 'VIEW_SM_ERROR',
};
export const VIEW_MPO_CONSTANT = {
  VIEW_MPO_LOADING: 'VIEW_MPO_LOADING',
  VIEW_MPO_SUCCESS: 'VIEW_MPO_SUCCESS',
  VIEW_MPO_ERROR: 'VIEW_MPO_ERROR',
};

export const CREATE_ADMIN_CONSTANT = {
    CREATE_ADMIN_LOADING: 'CREATE_ADMIN_LOADING',
    CREATE_ADMIN_SUCCESS: 'CREATE_ADMIN_SUCCESS',
    CREATE_ADMIN_ERROR: 'CREATE_ADMIN_ERROR',
  };
  export const CREATE_DIRECTOR_CONSTANT = {
    CREATE_DIRECTOR_LOADING: 'CREATE_DIRECTOR_LOADING',
    CREATE_DIRECTOR_SUCCESS: 'CREATE_DIRECTOR_SUCCESS',
    CREATE_DIRECTOR_ERROR: 'CREATE_DIRECTOR_ERROR',
  };
  
  export const CREATE_DEPO_CONSTANT = {
    CREATE_DEPO_LOADING: 'CREATE_DEPO_LOADING',
    CREATE_DEPO_SUCCESS: 'CREATE_DEPO_SUCCESS',
    CREATE_DEPO_ERROR: 'CREATE_DEPO_ERROR',
  };
  export const CREATE_DELIVERYSTAFF_CONSTANT = {
    CREATE_DELIVERYSTAFF_LOADING: 'CREATE_DELIVERYSTAFF_LOADING',
    CREATE_DELIVERYSTAFF_SUCCESS: 'CREATE_DELIVERYSTAFF_SUCCESS',
    CREATE_DELIVERYSTAFF_ERROR: 'CREATE_DELIVERYSTAFF_ERROR',
  };
  export const CREATE_AM_CONSTANT = {
    CREATE_AM_LOADING: 'CREATE_AM_LOADING',
    CREATE_AM_SUCCESS: 'CREATE_AM_SUCCESS',
    CREATE_AM_ERROR: 'CREATE_AM_ERROR',
  };
  export const CREATE_RSM_CONSTANT = {
    CREATE_RSM_LOADING: 'CREATE_RSM_LOADING',
    CREATE_RSM_SUCCESS: 'CREATE_RSM_SUCCESS',
    CREATE_RSM_ERROR: 'CREATE_RSM_ERROR',
  };
  export const CREATE_SM_CONSTANT = {
    CREATE_SM_LOADING: 'CREATE_SM_LOADING',
    CREATE_SM_SUCCESS: 'CREATE_SM_SUCCESS',
    CREATE_SM_ERROR: 'CREATE_SM_ERROR',
  };
  export const CREATE_MPO_CONSTANT = {
    CREATE_MPO_LOADING: 'CREATE_MPO_LOADING',
    CREATE_MPO_SUCCESS: 'CREATE_MPO_SUCCESS',
    CREATE_MPO_ERROR: 'CREATE_MPO_ERROR',
  };
  export const UPDATE_ADMIN_CONSTANT = {
    UPDATE_ADMIN_LOADING: 'UPDATE_ADMIN_LOADING',
    UPDATE_ADMIN_SUCCESS: 'UPDATE_ADMIN_SUCCESS',
    UPDATE_ADMIN_ERROR: 'UPDATE_ADMIN_ERROR',
  };
  export const UPDATE_DIRECTOR_CONSTANT = {
    UPDATE_DIRECTOR_LOADING: 'UPDATE_DIRECTOR_LOADING',
    UPDATE_DIRECTOR_SUCCESS: 'UPDATE_DIRECTOR_SUCCESS',
    UPDATE_DIRECTOR_ERROR: 'UPDATE_DIRECTOR_ERROR',
  };
  
  export const UPDATE_DEPO_CONSTANT = {
    UPDATE_DEPO_LOADING: 'UPDATE_DEPO_LOADING',
    UPDATE_DEPO_SUCCESS: 'UPDATE_DEPO_SUCCESS',
    UPDATE_DEPO_ERROR: 'UPDATE_DEPO_ERROR',
  };
  export const UPDATE_DELIVERYSTAFF_CONSTANT = {
    UPDATE_DELIVERYSTAFF_LOADING: 'UPDATE_DELIVERYSTAFF_LOADING',
    UPDATE_DELIVERYSTAFF_SUCCESS: 'UPDATE_DELIVERYSTAFF_SUCCESS',
    UPDATE_DELIVERYSTAFF_ERROR: 'UPDATE_DELIVERYSTAFF_ERROR',
  };
  export const UPDATE_AM_CONSTANT = {
    UPDATE_AM_LOADING: 'UPDATE_AM_LOADING',
    UPDATE_AM_SUCCESS: 'UPDATE_AM_SUCCESS',
    UPDATE_AM_ERROR: 'UPDATE_AM_ERROR',
  };
  export const UPDATE_RSM_CONSTANT = {
    UPDATE_RSM_LOADING: 'UPDATE_RSM_LOADING',
    UPDATE_RSM_SUCCESS: 'UPDATE_RSM_SUCCESS',
    UPDATE_RSM_ERROR: 'UPDATE_RSM_ERROR',
  };
  export const UPDATE_SM_CONSTANT = {
    UPDATE_SM_LOADING: 'UPDATE_SM_LOADING',
    UPDATE_SM_SUCCESS: 'UPDATE_SM_SUCCESS',
    UPDATE_SM_ERROR: 'UPDATE_SM_ERROR',
  };
  export const UPDATE_MPO_CONSTANT = {
    UPDATE_MPO_LOADING: 'UPDATE_MPO_LOADING',
    UPDATE_MPO_SUCCESS: 'UPDATE_MPO_SUCCESS',
    UPDATE_MPO_ERROR: 'UPDATE_MPO_ERROR',
  };
















export const SET_USER_FROM_LOCAL = 'SET_USER_FROM_LOCAL';



















export const VIEW_RESCHEDULE_REQUEST = {
  VIEW_RESCHEDULE_REQUEST_LOADING: 'VIEW_RESCHEDULE_REQUEST_LOADING',
  VIEW_RESCHEDULE_REQUEST_SUCESS: 'VIEW_RESCHEDULE_REQUEST_SUCESS',
  VIEW_RESCHEDULE_REQUEST_ERROR: 'VIEW_RESCHEDULE_REQUEST_ERROR',
};
export const UPDATE_RESCHEDULE_REQUEST = {
  UPDATE_RESCHEDULE_REQUEST_LOADING: 'UPDATE_RESCHEDULE_REQUEST_LOADING',
  UPDATE_RESCHEDULE_REQUEST_SUCESS: 'UPDATE_RESCHEDULE_REQUEST_SUCESS',
  UPDATE_RESCHEDULE_REQUEST_ERROR: 'UPDATE_RESCHEDULE_REQUEST_ERROR',
};
export const GET_AVILABLE_SLOTS = {
  GET_AVILABLE_SLOTS_LOADING: 'GET_AVILABLE_SLOTS_LOADING',
  GET_AVILABLE_SLOTS_SUCESS: 'GET_AVILABLE_SLOTS_SUCESS',
  GET_AVILABLE_SLOTS_ERROR: 'GET_AVILABLE_SLOTS_ERROR',
};
export const VIEW_CURRENT_ORDER_CONSTANTS = {
  VIEW_CURRENT_ORDER_LOADING: 'VIEW_CURRENT_ORDER_LOADING',
  VIEW_CURRENT_ORDER_SUCESS: 'VIEW_CURRENT_ORDER_SUCESS',
  VIEW_CURRENT_ORDER_ERROR: 'VIEW_CURRENT_ORDER_ERROR',
};
export const VIEW_REMOVAL_REQUEST_CONSTANTS = {
  VIEW_REMOVAL_REQUEST_LOADING: 'VIEW_REMOVAL_REQUEST_LOADING',
  VIEW_REMOVAL_REQUEST_SUCESS: 'VIEW_REMOVAL_REQUEST_SUCESS',
  VIEW_REMOVAL_REQUEST_ERROR: 'VIEW_REMOVAL_REQUEST_ERROR',
};
export const ACCEPT_REMOVAL_REQUEST_CONSTANTS = {
  ACCEPT_REMOVAL_REQUEST_LOADING: 'ACCEPT_REMOVAL_REQUEST_LOADING',
  ACCEPT_REMOVAL_REQUEST_SUCESS: 'ACCEPT_REMOVAL_REQUEST_SUCESS',
  ACCEPT_REMOVAL_REQUEST_ERROR: 'ACCEPT_REMOVAL_REQUEST_ERROR',
};
export const REJECT_REMOVAL_REQUEST_CONSTANTS = {
  REJECT_REMOVAL_REQUEST_LOADING: 'REJECT_REMOVAL_REQUEST_LOADING',
  REJECT_REMOVAL_REQUEST_SUCESS: 'REJECT_REMOVAL_REQUEST_SUCESS',
  REJECT_REMOVAL_REQUEST_ERROR: 'REJECT_REMOVAL_REQUEST_ERROR',
};
export const VIEW_CURRENT_REMOVAL_REQUEST_CONSTANTS = {
  VIEW_CURRENT_REMOVAL_REQUEST_LOADING: 'VIEW_CURRENT_REMOVAL_REQUEST_LOADING',
  VIEW_CURRENT_REMOVAL_REQUEST_SUCESS: 'VIEW_CURRENT_REMOVAL_REQUEST_SUCESS',
  VIEW_CURRENT_REMOVAL_REQUEST_ERROR: 'VIEW_CURRENT_REMOVAL_REQUEST_ERROR',
};
export const VIEW_CURRENT_APPOINMTENT_REQUEST_CONSTANTS = {
  VIEW_CURRENT_APPOINMTENT_REQUEST_LOADING:
    'VIEW_CURRENT_APPOINMTENT_REQUEST_LOADING',
  VIEW_CURRENT_APPOINMTENT_REQUEST_SUCESS:
    'VIEW_CURRENT_APPOINMTENT_REQUEST_SUCESS',
  VIEW_CURRENT_APPOINMTENT_REQUEST_ERROR:
    'VIEW_CURRENT_APPOINMTENT_REQUEST_ERROR',
};
export const CANCAL_APPOINTMENT_REQEUEST = {
  CANCAL_APPOINTMENT_REQEUEST_LOADING: 'CANCAL_APPOINTMENT_REQEUEST_LOADING',
  CANCAL_APPOINTMENT_REQEUEST_SUCESS: 'CANCAL_APPOINTMENT_REQEUEST_SUCESS',
  CANCAL_APPOINTMENT_REQEUEST_ERROR: 'CANCAL_APPOINTMENT_REQEUEST_ERROR',
};
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_PASSWORD_CONSTANT = {
  CHANGE_PASSWORD_LOADING: 'CHANGE_PASSWORD_LOADING',
  CHANGE_PASSWORD_SUCESS: 'CHANGE_PASSWORD_SUCESS',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
};
export const CREATE_DOCTOR_CONSTANT = {
  CREATE_DOCTOR_LOADING: 'CREATE_DOCTOR_LOADING',
  CREATE_DOCTOR_SUCESS: 'CREATE_DOCTOR_SUCESS',
  CREATE_DOCTOR_ERROR: 'CREATE_DOCTOR_ERROR',
};
export const VIEW_DOCTOR_CONSTANT = {
  VIEW_DOCTOR_LOADING: 'VIEW_DOCTOR_LOADING',
  VIEW_DOCTOR_SUCESS: 'VIEW_DOCTOR_SUCESS',
  VIEW_DOCTOR_ERROR: 'VIEW_DOCTOR_ERROR',
};
export const VIEW_CURRENT_DOCTOR_CONSTANT = {
  VIEW_CURRENT_DOCTOR_LOADING: 'VIEW_CURRENT_DOCTOR_LOADING',
  VIEW_CURRENT_DOCTOR_SUCESS: 'VIEW_CURRENT_DOCTOR_SUCESS',
  VIEW_CURRENT_DOCTOR_ERROR: 'VIEW_CURRENT_DOCTOR_ERROR',
};
export const UPDATE_DOCTOR_CONSTANT = {
  UPDATE_DOCTOR_LOADING: 'UPDATE_DOCTOR_LOADING',
  UPDATE_DOCTOR_SUCESS: 'UPDATE_DOCTOR_SUCESS',
  UPDATE_DOCTOR_ERROR: 'UPDATE_DOCTOR_ERROR',
};
export const CREATE_ADMINISTRATOR_CONSTANT = {
  CREATE_ADMINISTRATOR_LOADING: 'CREATE_ADMINISTRATOR_LOADING',
  CREATE_ADMINISTRATOR_SUCESS: 'CREATE_ADMINISTRATOR_SUCESS',
  CREATE_ADMINISTRATOR_ERROR: 'CREATE_ADMINISTRATOR_ERROR',
};
export const UPDATE_ADMINISTRATOR_CONSTANT = {
  UPDATE_ADMINISTRATOR_LOADING: 'UPDATE_ADMINISTRATOR_LOADING',
  UPDATE_ADMINISTRATOR_SUCESS: 'UPDATE_ADMINISTRATOR_SUCESS',
  UPDATE_ADMINISTRATOR_ERROR: 'UPDATE_ADMINISTRATOR_ERROR',
};
export const VIEW_ADMINISTRATOR_CONSTANT = {
  VIEW_ADMINISTRATOR_LOADING: 'VIEW_ADMINISTRATOR_LOADING',
  VIEW_ADMINISTRATOR_SUCESS: 'VIEW_ADMINISTRATOR_SUCESS',
  VIEW_ADMINISTRATOR_ERROR: 'VIEW_ADMINISTRATOR_ERROR',
};
export const VIEW_CURRENT_ADMINISTRATOR_CONSTANT = {
  VIEW_CURRENT_ADMINISTRATOR_LOADING: 'VIEW_CURRENT_ADMINISTRATOR_LOADING',
  VIEW_CURRENT_ADMINISTRATOR_SUCESS: 'VIEW_CURRENT_ADMINISTRATOR_SUCESS',
  VIEW_CURRENT_ADMINISTRATOR_ERROR: 'VIEW_CURRENT_ADMINISTRATOR_ERROR',
};

export const CREATE_LABADMIN_CONSTANT = {
  CREATE_LABADMIN_LOADING: 'CREATE_LABADMIN_LOADING',
  CREATE_LABADMIN_SUCESS: 'CREATE_LABADMIN_SUCESS',
  CREATE_LABADMIN_ERROR: 'CREATE_LABADMIN_ERROR',
};
export const UPDATE_LABADMIN_CONSTANT = {
  UPDATE_LABADMIN_LOADING: 'UPDATE_LABADMIN_LOADING',
  UPDATE_LABADMIN_SUCESS: 'UPDATE_LABADMIN_SUCESS',
  UPDATE_LABADMIN_ERROR: 'UPDATE_LABADMIN_ERROR',
};

export const VIEW_LABADMIN_CONSTANT = {
  VIEW_LABADMIN_LOADING: 'VIEW_LABADMIN_LOADING',
  VIEW_LABADMIN_SUCESS: 'VIEW_LABADMIN_SUCESS',
  VIEW_LABADMIN_ERROR: 'VIEW_LABADMIN_ERROR',
};
export const VIEW_CURRENT_LABADMIN_CONSTANT = {
  VIEW_CURRENT_LABADMIN_LOADING: 'VIEW_CURRENT_LABADMIN_LOADING',
  VIEW_CURRENT_LABADMIN_SUCESS: 'VIEW_CURRENT_LABADMIN_SUCESS',
  VIEW_CURRENT_LABADMIN_ERROR: 'VIEW_CURRENT_LABADMIN_ERROR',
};

export const CREATE_PHARMACY_CONSTANT = {
  CREATE_PHARMACY_LOADING: 'CREATE_PHARMACY_LOADING',
  CREATE_PHARMACY_SUCESS: 'CREATE_PHARMACY_SUCESS',
  CREATE_PHARMACY_ERROR: 'CREATE_PHARMACY_ERROR',
};
export const UPDATE_PHARMACY_CONSTANT = {
  UPDATE_PHARMACY_LOADING: 'UPDATE_PHARMACY_LOADING',
  UPDATE_PHARMACY_SUCESS: 'UPDATE_PHARMACY_SUCESS',
  UPDATE_PHARMACY_ERROR: 'UPDATE_PHARMACY_ERROR',
};

export const VIEW_PHARMACY_CONSTANT = {
  VIEW_PHARMACY_LOADING: 'VIEW_PHARMACY_LOADING',
  VIEW_PHARMACY_SUCESS: 'VIEW_PHARMACY_SUCESS',
  VIEW_PHARMACY_ERROR: 'VIEW_PHARMACY_ERROR',
};
export const VIEW_CURRENT_PHARMACY_CONSTANT = {
  VIEW_CURRENT_PHARMACY_LOADING: 'VIEW_CURRENT_PHARMACY_LOADING',
  VIEW_CURRENT_PHARMACY_SUCESS: 'VIEW_CURRENT_PHARMACY_SUCESS',
  VIEW_CURRENT_PHARMACY_ERROR: 'VIEW_CURRENT_PHARMACY_ERROR',
};

export const CREATE_SUPERADMIN_CONSTANT = {
  CREATE_SUPERADMIN_LOADING: 'CREATE_SUPERADMIN_LOADING',
  CREATE_SUPERADMIN_SUCESS: 'CREATE_SUPERADMIN_SUCESS',
  CREATE_SUPERADMIN_ERROR: 'CREATE_SUPERADMIN_ERROR',
};
export const UPDATE_SUPERADMIN_CONSTANT = {
  UPDATE_SUPERADMIN_LOADING: 'UPDATE_SUPERADMIN_LOADING',
  UPDATE_SUPERADMIN_SUCESS: 'UPDATE_SUPERADMIN_SUCESS',
  UPDATE_SUPERADMIN_ERROR: 'UPDATE_SUPERADMIN_ERROR',
};

export const VIEW_SUPERADMIN_CONSTANT = {
  VIEW_SUPERADMIN_LOADING: 'VIEW_SUPERADMIN_LOADING',
  VIEW_SUPERADMIN_SUCESS: 'VIEW_SUPERADMIN_SUCESS',
  VIEW_SUPERADMIN_ERROR: 'VIEW_SUPERADMIN_ERROR',
};
export const VIEW_CURRENT_SUPERADMIN_CONSTANT = {
  VIEW_CURRENT_SUPERADMIN_LOADING: 'VIEW_CURRENT_SUPERADMIN_LOADING',
  VIEW_CURRENT_SUPERADMIN_SUCESS: 'VIEW_CURRENT_SUPERADMIN_SUCESS',
  VIEW_CURRENT_SUPERADMIN_ERROR: 'VIEW_CURRENT_SUPERADMIN_ERROR',
};

export const GET_DEPARTMENT_CONSTANT = {
  GET_DEPARTMENT_LOADING: 'GET_DEPARTMENT_LOADING',
  GET_DEPARTMENT_SUCESS: 'GET_DEPARTMENT_SUCESS',
  GET_DEPARTMENT_ERROR: 'GET_DEPARTMENT_ERROR',
};

export const CREATE_PATIENT_CONSTANT = {
  CREATE_PATIENT_LOADING: 'CREATE_PATIENT_LOADING',
  CREATE_PATIENT_SUCESS: 'CREATE_PATIENT_SUCESS',
  CREATE_PATIENT_ERROR: 'CREATE_PATIENT_ERROR',
};
export const UPDATE_PATIENT_CONSTANT = {
  UPDATE_PATIENT_LOADING: 'UPDATE_PATIENT_LOADING',
  UPDATE_PATIENT_SUCESS: 'UPDATE_PATIENT_SUCESS',
  UPDATE_PATIENT_ERROR: 'UPDATE_PATIENT_ERROR',
};
export const VIEW_PATIENT_CONSTANT = {
  VIEW_PATIENT_LOADING: 'VIEW_PATIENT_LOADING',
  VIEW_PATIENT_SUCESS: 'VIEW_PATIENT_SUCESS',
  VIEW_PATIENT_ERROR: 'VIEW_PATIENT_ERROR',
};
export const VIEW_CURRENT_PATIENT_CONSTANT = {
  VIEW_CURRENT_PATIENT_LOADING: 'VIEW_CURRENT_PATIENT_LOADING',
  VIEW_CURRENT_PATIENT_SUCESS: 'VIEW_CURRENT_PATIENT_SUCESS',
  VIEW_CURRENT_PATIENT_ERROR: 'VIEW_CURRENT_PATIENT_ERROR',
};

export const UPDATE_ORDER_CONSTANT = {
  UPDATE_ORDER_LOADING: 'UPDATE_ORDER_LOADING',
  UPDATE_ORDER_SUCESS: 'UPDATE_ORDER_SUCESS',
  UPDATE_ORDER_ERROR: 'UPDATE_ORDER_ERROR',
};

export const VIEW_TEST_CONSTANT = {
  VIEW_TEST_LOADING: 'VIEW_TEST_LOADING',
  VIEW_TEST_SUCESS: 'VIEW_TEST_SUCESS',
  VIEW_TEST_ERROR: 'VIEW_TEST_ERROR',
};

export const UPDATE_TEST_CONSTANT = {
  UPDATE_TEST_LOADING: 'UPDATE_TEST_LOADING',
  UPDATE_TEST_SUCESS: 'UPDATE_TEST_SUCESS',
  UPDATE_TEST_ERROR: 'UPDATE_TEST_ERROR',
};

export const UPDATE_CATEGORY_CONSTANT = {
  UPDATE_CATEGORY_LOADING: 'UPDATE_CATEGORY_LOADING',
  UPDATE_CATEGORY_SUCESS: 'UPDATE_CATEGORY_SUCESS',
  UPDATE_CATEGORY_ERROR: 'UPDATE_CATEGORY_ERROR',
};
export const READR_CATEGORY_CONSTANT = {
  READR_CATEGORY_LOADING: 'READR_CATEGORY_LOADING',
  READR_CATEGORY_SUCESS: 'READR_CATEGORY_SUCESS',
  READR_CATEGORY_ERROR: 'READR_CATEGORY_ERROR',
};
export const CREATE_TEST_CONSTANT = {
  CREATE_TEST_LOADING: 'CREATE_TEST_LOADING',
  CREATE_TEST_SUCESS: 'CREATE_TEST_SUCESS',
  CREATE_TEST_ERROR: 'CREATE_TEST_ERROR',
};
export const CREATE_CATEGORY_CONSTANT = {
  CREATE_CATEGORY_LOADING: 'CREATE_CATEGORY_LOADING',
  CREATE_CATEGORY_SUCESS: 'CREATE_CATEGORY_SUCESS',
  CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',
};

export const VIEW_MEDICINE_CONSTANT = {
  VIEW_MEDICINES_LOADING: 'VIEW_MEDICINES_LOADING',
  VIEW_MEDICINES_SUCESS: 'VIEW_MEDICINES_SUCESS',
  VIEW_MEDICINES_ERROR: 'VIEW_MEDICINES_ERROR',
};
export const CREATE_MEDICINE_CONSTANT = {
  CREATE_MEDICINES_LOADING: 'CREATE_MEDICINES_LOADING',
  CREATE_MEDICINES_SUCESS: 'CREATE_MEDICINES_SUCESS',
  CREATE_MEDICINES_ERROR: 'CREATE_MEDICINES_ERROR',
};
export const UPDATE_MEDICINE_CONSTANT = {
  UPDATE_MEDICINES_LOADING: 'UPDATE_MEDICINES_LOADING',
  UPDATE_MEDICINES_SUCESS: 'UPDATE_MEDICINES_SUCESS',
  UPDATE_MEDICINES_ERROR: 'UPDATE_MEDICINES_ERROR',
};

export const VIEW_REPORT_CONSTANT = {
  VIEW_REPORT_LOADING: 'VIEW_REPORT_LOADING',
  VIEW_REPORT_SUCCESS: 'VIEW_REPORT_SUCCESS',
  VIEW_REPORT_ERROR: 'VIEW_REPORT_ERROR',
};

export const REGION_CLASSIFICAION_CONSTANT = {
  CREATE_REGION_CLASSIFICAION_LOADING: 'CREATE_REGION_CLASSIFICAION_LOADING',
  CREATE_REGION_CLASSIFICAION_SUCCESS: 'CREATE_REGION_CLASSIFICAION_SUCCESS',
  CREATE_REGION_CLASSIFICAION_ERROR: 'CREATE_REGION_CLASSIFICAION_ERROR',
};
export const READ_REGION_CONSTANT = {
  READ_REGION_LOADING: 'READ_REGION_LOADING',
  READ_REGION_SUCCESS: 'READ_REGION_SUCCESS',
  READ_REGION_ERROR: 'READ_REGION_ERROR',
};
export const EDIT_REGION_CLASSIFICATION = {
  EDIT_REGION_CLASSIFICATION_LOADING: 'EDIT_REGION_CLASSIFICATION_LOADING',
  EDIT_REGION_CLASSIFICATION_SUCCESS: 'EDIT_REGION_CLASSIFICATION_SUCCESS',
  EDIT_REGION_CLASSIFICATION_ERROR: 'EDIT_REGION_CLASSIFICATION_ERROR',
};



export const VIEW_ORDER_CONSTANTS = {
  VIEW_ORDER_LOADING: 'VIEW_ORDER_LOADING',
  VIEW_ORDER_SUCESS: 'VIEW_ORDER_SUCESS',
  VIEW_ORDER_ERROR: 'VIEW_ORDER_ERROR',
};




export const ORDER_CONSTANTS = {
  ORDER_LOADING: 'ORDER_LOADING',
  ORDER_SUCESS: 'ORDER_SUCESS',
  ORDER_ERROR: 'ORDER_ERROR',
};





